title: CreateWebhookConfiguration
description: The payload for registering a new webhook configuration.
type: object
x-internal: false
required:
  - url
  - enabled
  - authentication
properties:
  url:
    type: string
    description: 'The URL we''ll send webhook notifications, must be HTTPS.'
    example: 'https://your-url-to-receive-webhook.com/12345'
  enabled:
    type: boolean
    description: Whether the webhook subscription is currently active
    default: false
  authentication:
    description: The authentication details used to secure delivery of the webhook.
    type: object
    required:
      - apiKey
    properties:
      apiKey:
        type: string
        description: A value used to identify this webhook. Subsequent webhook payloads will include a HTTP header 'x-roller-apikey' with this value.
        example: CRM Trigger Webhook 002
  webhooks:
    description: The set of webhook subscriptions and their configuration.
    type: object
    properties:
      booking:
        type: object
        required:
          - events
        properties:
          events:
            type: array
            description: Receive payloads for specific events
            items:
              enum:
                - Created
                - Updated
                - Cancelled
          include:
            type: object
            description: Additional properties that can be returned with the webhook payload (optional)
            properties:
              externalId:
                type: boolean
                description: An ID that can be attached to bookings generated external of ROLLER (eg. 3rd party ticket sales or API created bookings)
              tickets:
                type: boolean
                description: Return information about specific tickets in the booking such as ticket ID and ticket holder name
              membershipDetail:
                type: boolean
                description: Return information about the status of memberships in the booking (if applicable)
              locations:
                type: boolean
                description: Return information about which resource each ticket in the booking reserves capaci
              customerFlags:
                type: boolean
                description: Return information on any guest flags that may be assigned to the guest
              payments:
                type: boolean
                description: Return information on any payment records that may be against the booking
          filter:
            type: object
            description: Conditional filters on what triggers the webhook (optional).
            properties:
              channels:
                type: array
                items:
                  $ref: ./SalesChannel.yaml
              productTypes:
                type: array
                description: Filter for bookings for specific product types.
                items:
                  $ref: ./WebhookFilterProductType.yaml
              productIds:
                type: array
                description: Filter for bookings for specific products by Product ID
                uniqueItems: true
                items:
                  type: integer
                  example: 42331
              productCategory:
                type: string
                description: Filter for bookings for products in a specific product category
                example: Entry Tickets
      redemption:
        type: object
        required:
          - events
        properties:
          events:
            type: array
            description: Receive payloads for specific events
            items:
              enum:
                - Created
          include:
            type: object
            description: Additional properties that can be returned with the webhook payload (optional)
            properties:
              membershipDetail:
                type: boolean
                description: Return information about the status of memberships in the booking (if applicable)
              multiPassDetail:
                type: boolean
                description: Returns information about the multi-pass product (if applicable)
          filter:
            type: object
            description: Conditional filters on what triggers the webhook (optional).
            properties:
              productIds:
                type: array
                description: Filter for redemptions of specific products by Product ID
                items:
                  type: integer
                  example: 42331
              productCategory:
                type: string
                description: Filter for redemptions of specific products belonging to a product category
                example: Entry Tickets
      customer:
        type: object
        required:
          - events
        properties:
          events:
            description: Receive payloads for specific events
            type: array
            items:
              enum:
                - Created
                - Updated
          include:
            type: object
            description: Additional properties that can be returned with the webhook payload (optional)
            properties:
              flags:
                type: boolean
                description: Return information on any guest flags that may be assigned to the guest
      bulkExport:
        type: object
        required:
          - events
        properties:
          events:
            type: array
            description: Receive payloads for specific events
            items:
              enum:
                - Created
      signedWaiver:
        type: object
        required:
          - events
        properties:
          events:
            type: array
            description: Receive payloads for specific events
            items:
              enum:
                - Created
      paymentLink:
        type: object
        required:
          - events
        properties:
          events:
            type: array
            description: Receive payloads for specific events
            items:
              enum:
                - Created
