title: ProductAvailability
x-stoplight:
  id: cp5hunh2zux29
type: object
description: Product variation (ticket type) availability
properties:
  date:
    type: string
    description: 'Availability date in the format: `yyyy-MM-dd`'
    example: '2025-07-14'
    x-stoplight:
      id: edf8hggcvfxuo
  onlineSalesOpen:
    type: boolean
    description: Whether the product is within its sale period
    example: true
    x-stoplight:
      id: lw91qcx66xorf
  allocations:
    type: array
    items:
      $ref: ./ProductCapacityAllocation.yaml
      x-stoplight:
        id: ozn0zfjvidqip
    x-stoplight:
      id: yn3p1b4yx45sy
