title: ProductAvailability
type: object
description: Product variation (ticket type) availability
properties:
  date:
    type: string
    description: 'Availability date in the format: `yyyy-MM-dd`'
    example: '2025-07-14'
  onlineSalesOpen:
    type: boolean
    description: Whether the product is within its sale period
    example: true
  allocations:
    description: The capacity allocations available for the product.
    type: array
    items:
      $ref: ./ProductCapacityAllocation.yaml
