title: ProductSession
type: object
description: Product variation (ticket type) availability for products that support session times
properties:
  date:
    type: string
    description: 'Session availability date in the format: `yyyy-MM-dd`'
    example: '2025-07-14'
  name:
    type: string
    description: Session name
    example: '1:30 pm'
  startTime:
    type: string
    description: 'Session start time in the format: `HH:mm`'
    example: '13:30'
  endTime:
    type: string
    description: 'Session end time in the format: `HH:mm`'
    example: '15:30'
  capacityRemaining:
    type:
      - integer
      - 'null'
    description: "Summary of remaining resource capacity for display purposes\r\n\r\n- Null value means unlimited capacity\r\n- This value varies depending on the type of attached resources\r\n\r\nSee `allocations` for more detailed resource capacity"
    example: 60
  onlineSalesOpen:
    type: boolean
    description: Whether the product is within its sale period
  resourceCapacityRemaining:
    type:
      - integer
      - 'null'
    description: Summary of remaining resource capacity. `null` value means no single booking resources are attached to this session.
  ticketCapacityRemaining:
    type:
      - integer
      - 'null'
    description: Summary of remaining ticket capacity. `null` value means unlimited capacity.
  allocations:
    description: The capacity allocations available for the session.
    type: array
    items:
      $ref: ./ProductCapacityAllocation.yaml
  remainingSessionCapacity:
    type:
      - integer
      - 'null'
    deprecated: true
    description: This has been replaced by other capacity properties
    example: 0
