title: ProductCapacityAllocation
type: object
description: Remaining product variation (ticket type) capacity
properties:
  productId:
    type: string
    description: Product ID
    example: '107400'
  capacityRemaining:
    type:
      - integer
      - 'null'
    description: "Summary of remaining resource capacity for display purposes\r\n\r\n- Null value means unlimited capacity\r\n- If it is a multi-booking resource, this is the total capacity remaining\r\n- If it is a single-booking type resource, this is the total number of different available resources\r\n  - eg: You have 3 single-booking party room resources that hold 20 people each, hence `capacityRemaining` = 3\r\n\r\nSee `locations` (and `resourceTimes` for time-based products)  for more detail."
    example: 3
  bookableCapacityRemaining:
    type:
      - integer
      - 'null'
    description: "Resource capacity remaining\r\n\r\n- Null value means unlimited capacity\r\n- If it is a multi-booking resource, this is the total capacity remaining\r\n- If it is a single-booking type resource, this is the total capacity of all different available resources\r\n  - eg: You have 3 single-booking party room resources that hold 20 people each, hence `bookingCapacityRemaining` = 60\r\n  - eg: Furthermore if the product setup limits resources to \"Max Per Booking\" of 2, then `bookingCapacityRemaining` = 40\r\n"
    example: 60
  locations:
    type: array
    description: Resources connected to the product
    items:
      $ref: ./ProductLocation.yaml
  resourceTimes:
    description: The resource time usages associated with the allocation.
    type: array
    items:
      $ref: ./ProductResourceTimeUsage.yaml
