title: ProductLocation
type: object
description: Configuration of resource(s) attached to the product
properties:
  id:
    type: string
    description: Resource ID
    example: '30539'
  allowMultipleBookings:
    type: boolean
    description: 'If this is false, this is a single booking resource type'
  bookingRestriction:
    $ref: ./LocationBookingRestriction.yaml
  times:
    description: The times at which the product is available at this location.
    type: array
    items:
      $ref: ./LocationTime.yaml
  capacity:
    type:
      - integer
      - 'null'
    example: 100
    description: Total resource capacity
