title: ProductLocationTime
type: object
description: "Specification for allocating capacity for a specified time, and resource(s)"
properties:
  startMinutes:
    type: integer
    description: "The number of minutes after the session begins, to start consuming capacity from the specified resource(s)"
    example: 0
  endMinutes:
    type: integer
    description: "The number of minutes after the session begins, to stop consuming capacity from the specified resource(s)"
    example: 60
  locationIds:
    type: array
    description: List of resource IDs to consume capacity from
    items:
      type: string
      example: "30539"
