title: ProductInfo
type: object
description: Details of the product variation (ticket type) on offer
properties:
  id:
    type: string
    description: Product ID
    example: '107400'
  name:
    type: string
    description: Product name
    example: Adult Ticket
    maxLength: 75
  description:
    type: string
    description: Brief description of the product variation (ticket type)
    example: Adult tickets are for individuals 13 years and older
    maxLength: 150
  imageUrl:
    type: string
    description: Product image URL
    example: 'https://someimage.com/10002'
  cost:
    type: number
    description: Product cost
    example: 24.99
  tax:
    type: number
    description: Tax percentage used to calculate the tax amount
    example: 7.5
  isTaxInclusive:
    type: boolean
    description: 'When true, the product cost already includes the tax amount. When false, tax will be added to the cost.'
  isSuspended:
    type: boolean
    description: 'For stock type products, whether sale has been suspended'
  locations:
    description: The locations at which the product is available.
    type: array
    items:
      $ref: ./ProductLocation.yaml
  recurringSessionDates:
    type: array
    description: 'For recurring pass type products, the dates of each session in the format: `yyyy-MM-dd`'
    items:
      type: string
      example: '2025-07-14'
  remainingRecurringSessions:
    type:
      - integer
      - 'null'
    description: The number of sessions remaining for a recurring pass type product
    example: 4
