title: ProductResourceTimeUsage
allOf:
  - $ref: ./LocationTime.yaml
  - type: object
    properties:
      remainingCapacity:
        type: integer
        description: 'Capacity remaining for attached resource(s) for the given time range '
        example: 12
      resourceIds:
        type: array
        description: List of resource IDs to consume capacity from
        items:
          type: integer
          example: 30539
description: Capacity remaining for attached resource(s) for the given time range
